# Generated by Django 4.2.4 on 2023-09-18 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pitche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('location', models.CharField(max_length=500)),
                ('name_of_supervisor', models.CharField(max_length=50)),
                ('phone_of_supervisor', models.CharField(max_length=11)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pitches.manager')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateField()),
                ('period', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=50)),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('timing', models.CharField(choices=[('one Hour', 'one hour'), ('Tow Hour', 'Tow hour'), ('Three Hour', 'Three hour')], max_length=50)),
                ('pitche', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pitches.pitche')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
