# Generated by Django 3.2.4 on 2023-08-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitche',
            name='location',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
