# Generated by Django 4.2.4 on 2023-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='pitche',
            name='name_of_supervisor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pitche',
            name='phone_of_supervisor',
            field=models.CharField(max_length=11),
        ),
    ]
