# Generated by Django 4.2.4 on 2023-09-24 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_alter_openinghours_pitche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='pitche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pitches.pitche'),
        ),
    ]
