# Generated by Django 4.2.4 on 2023-09-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0003_alter_openinghours_pitche'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='name_of_filed',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
