# Generated by Django 4.2.4 on 2023-09-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_openinghours_name_of_filed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='name_of_filed',
        ),
    ]
