# Generated by Django 4.2.4 on 2023-09-30 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0005_remove_openinghours_name_of_filed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['-made_on']},
        ),
    ]
