# Generated by Django 4.2.4 on 2023-10-04 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0006_alter_openinghours_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={},
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='made_on',
        ),
        migrations.RemoveField(
            model_name='openinghours',
            name='period',
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 15, 41, 59, 953659)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 15, 41, 59, 953659)),
        ),
    ]
