# Generated by Django 4.2.4 on 2023-10-04 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0008_city_alter_openinghours_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitche',
            name='city',
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 16, 50, 59, 356967)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 16, 50, 59, 356967)),
        ),
    ]
