# Generated by Django 4.2.4 on 2023-10-04 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0010_pitche_city_alter_openinghours_from_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 16, 53, 34, 932464)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 16, 53, 34, 932464)),
        ),
    ]
