# Generated by Django 4.2.4 on 2023-10-04 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0011_alter_openinghours_from_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitche',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 17, 1, 33, 312831)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 4, 17, 1, 33, 312831)),
        ),
    ]
