# Generated by Django 4.2.4 on 2023-10-15 19:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitches', '0013_alter_openinghours_from_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 22, 57, 29, 158620)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='timing',
            field=models.CharField(choices=[('one Hour', 'one hour'), ('Tow Hour', 'Tow hour'), ('Three Hour', 'Three hour'), ('Four Hour', 'Four hour')], max_length=50),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 15, 22, 57, 29, 158620)),
        ),
    ]
