# Generated by Django 4.2.7 on 2023-11-25 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0018_remove_openinghours_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 23, 57, 34, 889165)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 23, 57, 34, 889165)),
        ),
    ]
