# Generated by Django 4.2.7 on 2023-11-26 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0020_remove_openinghours_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='from_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 5, 47, 55, 894171)),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='to_hour',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 5, 47, 55, 894171)),
        ),
    ]
